name: Virtual Alpine with ZeroTier

on:
  workflow_dispatch:

jobs:
  run-virtual-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: 查看 GitHub Actions 运行环境
        run: |
          echo "### CPU 信息 ###"
          lscpu
          echo "### 内存信息 ###"
          free -h
          echo "### 磁盘信息 ###"
          df -h
          echo "### 操作系统信息 ###"
          uname -a

      - name: 下载并运行 Alpine Linux
        run: |
          sudo apt update
          sudo apt install -y busybox
          mkdir -p ~/alpine
          wget -qO- http://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/x86_64/alpine-minirootfs-3.18.4-x86_64.tar.gz | sudo tar -xz -C ~/alpine
          echo "Alpine Linux 解压完成"

      - name: 进入 Alpine 并查看系统信息
        run: |
          sudo chroot ~/alpine /bin/sh -c "
          echo '### Alpine Linux 运行环境 ###'
          uname -a
          echo '### Alpine Linux CPU 和内存 ###'
          free -h
          echo '### Alpine Linux 磁盘 ###'
          df -h
          echo '### Alpine Linux 网络 ###'
          ip a && ip route
          "

      - name: 运行 5 小时（等待手动停止）
        run: sleep 18000
