name: Virtual Alpine with ZeroTier

on:
  workflow_dispatch:

jobs:
  run-virtual-alpine:
    runs-on: ubuntu-latest
    steps:

      - name: 下载并运行 Alpine Linux
        run: |
          sudo apt update
          sudo apt install -y busybox curl
          mkdir -p ~/alpine
          curl -L -o alpine.tar.gz http://dl-cdn.alpinelinux.org/alpine/v3.18/releases/x86_64/alpine-minirootfs-3.18.4-x86_64.tar.gz
          ls -lh alpine.tar.gz
          tar -tzf alpine.tar.gz || (echo "文件损坏，下载失败！" && exit 1)
          tar -xzvf alpine.tar.gz -C ~/alpine
          echo "Alpine Linux 解压完成"

      - name: 测试网络连接和查看网络配置
        run: |
          sudo chroot ~/alpine /bin/sh -c "
          echo '### 测试网络连接 ###'
          ping -c 4 8.8.8.8 || (echo 'Ping 测试失败，网络可能不可用。' && exit 1)

          echo '### 查看网络配置 ###'
          ifconfig
          "

      - name: 安装 ZeroTier 并替换 planet 文件
        run: |
          sudo chroot ~/alpine /bin/sh -c "
          echo '### 配置 Alpine Linux ###'
          # 使用阿里云镜像源
          echo 'https://mirrors.aliyun.com/alpine/v3.18/main' > /etc/apk/repositories
          echo 'https://mirrors.aliyun.com/alpine/v3.18/community' >> /etc/apk/repositories
          # 添加备用源
          echo 'https://mirror.nju.edu.cn/alpine/v3.18/main' >> /etc/apk/repositories
          echo 'https://mirror.nju.edu.cn/alpine/v3.18/community' >> /etc/apk/repositories
          apk update

          echo '### 安装 openrc, ZeroTier 和 curl ###'
          apk add openrc zerotier-one curl

          echo '### 停止 ZeroTier 以替换 planet 文件 ###'
          service zerotier-one stop

          echo '### 下载并替换 planet 文件 ###'
          curl -L -o /var/lib/zerotier-one/planet http://www.linzifu.xyz:8081/planet
          chmod 644 /var/lib/zerotier-one/planet

          echo '### 启动 ZeroTier ###'
          service zerotier-one start

          echo '### 加入 ZeroTier 网络 ###'
          zerotier-cli join 645ae69a7238a4bd

          echo '### ZeroTier 运行状态 ###'
          zerotier-cli info
          "

      - name: 运行 5 小时（等待手动停止）
        run: sleep 18000